apiVersion: devjoes/v1
kind: AzureSecrets
metadata:
  name: default-name
vault: TestKeyVault
secrets:
- name: test
  namespace: test-ns
  keys:
  - TestSecret1=test-secret1
  - TestSecret2=test-secret2
- name: foo-and-bar
  keys:
  - FOO1=test-secret1
  - BAR1=test-secret2
- namespace: test-ns
  keys:
  - FOO2=test-secret1
  - BAR2=test-secret2