# This is a basic workflow to help you get started with Actions

name: Build image

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags: ['*']
    branches: [ temp ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref.replace(/\/?refs\/tags\//, '').replace(/\/?refs\/heads\//, '').replace(/"/g,'');
      - run: echo "a${FOO}b"
        env:
          FOO: ${{ steps.tag.outputs.result }}
  
      - name: Login
        uses: docker/login-action@v1.6.0
        with:
          username: joeshearn
          password: ${{ secrets.dockerhub_pass }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.2.1
        with:
          context: .
          tags: joeshearn/azure-secrets:${{ steps.tag.outputs.result }},joeshearn/azure-secrets:latest
          push: false
